# Generated by Django 4.2.4 on 2023-08-20 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('piece', '0002_alter_category_options_piece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to=settings.AUTH_USER_MODEL),
        ),
    ]
