# Generated by Django 4.2.4 on 2023-08-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0004_artist_show_delete_category_remove_piece_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='pricing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='piece',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
