# Generated by Django 4.2.4 on 2023-08-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0005_piece_pricing_alter_piece_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
