# Generated by Django 4.2.4 on 2023-08-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0007_show_closing'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='dimensions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
