# Generated by Django 4.2.4 on 2023-08-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0008_piece_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
