# Generated by Django 4.2.4 on 2023-08-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piece', '0009_piece_end_year_piece_start_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='end_year',
            field=models.IntegerField(default=2023),
            preserve_default=False,
        ),
    ]
